# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script:
    sleep 1
  displayName: 'Build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.Repository.LocalPath)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Packaging ZIP file'

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '$(VERACODE_API_ID)'
    apiKey: '$(VERACODE_API_KEY)'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(Build.Repository.LocalPath)/$(Build.BuildId).zip'
    createSandBox: false
    createProfile: true
    failTheBuildIfVeracodeScanDidNotInitiate: false
    scanStatusCheckInterval: '60'
    importResults: true
    failBuildOnPolicyFail: true
  displayName: 'Veracode Static Scan'

- script: |
    ls -lh
    echo DEPLOY
    sleep 2
  displayName: 'Deploy'