on: 
  push: 
    branches: [main]

jobs:
  veracode-auto-package:
    name: Veracode Auto Package
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Veracode CLI Download and Package
        env: 
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_KEY }}
        run: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode package --source . --output veracode-auto-pack-Web-dotnet-js.zip --trust
          ls -l
          
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: veracode_pack
          path: veracode-auto-pack-Web-dotnet-js.zip

  veracode-sast-pipeline-scan:
    runs-on: ubuntu-latest
    needs: veracode-auto-package
    name: Veracode SAST Pipeline Scan
    steps:
      - name: Get archive
        uses: actions/download-artifact@v2
        with:
          name: veracode_pack
          path: .

      - name: Pipeline scan action step
        run: |
          curl -LO https://repo1.maven.org/maven2/com/veracode/pipeline-scan/LATEST/pipeline-scan-LATEST.zip
          unzip pipeline-scan-LATEST.zip
          chmod 755 pipeline-scan.jar
          java -jar pipeline-scan.jar -vid ${{ secrets.VERACODE_ID }} -vkey ${{ secrets.VERACODE_KEY }} -f veracode-auto-pack-Web-dotnet-js.zip -fail_build false
